#!/usr/bin/env python3
"""Second half of the appendix data tables: the pre-registered statistics, sequential
search, ablations, shift severity and benchmark sanity checks. Emitted from the parquet
trees so the appendix cannot drift from the results."""
from __future__ import annotations
import glob, os
import numpy as np, pandas as pd
from scipy.stats import wilcoxon, rankdata

OUT="Formatting_Instructions_For_ICBINB_Failure_Modes_in_AI_for_Biology___NeurIPS_2026/appendix_tables2.tex"
P1A="artifacts/results/phase1a_pool/candidates"; GD="artifacts/results/exploratory/gdsc/phase1a/candidates"
ABL="artifacts/results/ablations"; SEV="artifacts/results/exploratory/shift_severity/candidates"
PRE="artifacts/results/phase1b_sequential/runs"; EX="artifacts/results/exploratory/phase1b_extra/runs"
GDB="artifacts/results/exploratory/gdsc/phase1b/runs"

def tex(s): return s.replace("_",r"\_")
def holm(p):
    p=np.asarray(p,float); n=len(p); a=np.empty(n); r=0.
    for i,k in enumerate(np.argsort(p)): r=max(r,(n-i)*p[k]); a[k]=min(r,1.)
    return a
def runs(root,cond,filt=True,need_val=True):
    out=[]
    for f in sorted(glob.glob(f"{root}/{cond}/*.parquet")):
        d=pd.read_parquet(f); d=d[d.status_train=="ok"]
        d=d[d.val_mse_std.notna()] if need_val else d[d.train_mse_std.notna()]
        if filt: d=d[(d.pred_std_test>=1e-6)&(d.dead_relu_frac<=0.5)]
        if len(d)>=5: out.append(d)
    return out
def sel(k,s):
    if s is None: return k.val_mse_std.idxmin()
    if s=="__tr": return k.train_mse_std.idxmin()
    if s=="__np": return k.n_params.idxmin()
    if s=="__or": return k.test_mse_std.idxmin()
    if s.startswith("t+"):
        c=s[2:]; o=k[k[c].notna()]
        return o.index[int(np.argmin(rankdata(o.train_mse_std)+rankdata(o[c])))]
    if s.startswith("+"):
        c=s[1:]; o=k[k[c].notna()]
        return o.index[int(np.argmin(rankdata(o.val_mse_std)+rankdata(o[c])))]
    return k[k[s].notna()][s].idxmin()

L=[r"% AUTO-GENERATED by scripts_icbinb/make_appendix_tex2.py -- do not hand-edit.",""]

# ---- the pre-registered confirmatory statistics, unfiltered vs filtered ------
FAM=[("cond7",P1A,"Lipophilicity (mismatch)"),("caco2_scaffold",P1A,"Caco2-Wang (scaffold)"),
     ("amylase",P1A,"FLIP2 Amylase"),("hydro",P1A,"FLIP2 Hydrophobic Core")]
L.append(r"\begin{table}[htbp]\centering\small\setlength{\tabcolsep}{4pt}")
L.append(r"\caption{The pre-registered confirmatory analysis, deployment MSE, Holm-corrected "
         r"across the four-condition family. Reported on the original unfiltered pools (the "
         r"pre-registered primary analysis) and again after the post-hoc degeneracy audit. "
         r"$\Delta$ is the paired median difference against validation; negative favours the "
         r"selector.}")
L.append(r"\label{tab:app-prereg}")
L.append(r"\begin{tabular}{llrrrrrr}\toprule")
L.append(r"& & \multicolumn{3}{c}{unfiltered (primary)} & \multicolumn{3}{c}{after audit} \\")
L.append(r"\cmidrule(lr){3-5}\cmidrule(lr){6-8}")
L.append(r"condition & selector & $\Delta$ & w/l & $p_{\text{Holm}}$ & $\Delta$ & w/l & $p_{\text{Holm}}$ \\\midrule")
for spec,lab in [("fg_legacy",r"\texttt{Proxy}"),("+fg_legacy",r"\texttt{Val+Proxy}")]:
    cell={}
    for filt in (False,True):
        ps,info=[],[]
        for c,root,_ in FAM:
            R=runs(root,c,filt)
            b=np.array([k.loc[sel(k,None),"test_mse_std"] for k in R])
            v=np.array([k.loc[sel(k,spec),"test_mse_std"] for k in R])
            d=v-b; d=d[np.isfinite(d)]
            ps.append(float(wilcoxon(d).pvalue) if np.any(d!=0) else 1.0)
            info.append((np.median(d),int((d<0).sum()),int((d>0).sum())))
        cell[filt]=(info,holm(ps))
    for i,(c,root,disp) in enumerate(FAM):
        u,uh=cell[False][0][i],cell[False][1][i]
        f,fh=cell[True][0][i],cell[True][1][i]
        star=lambda h: r"\textbf{%.3f}"%h if h<0.05 else "%.3f"%h
        L.append(f"{disp if i==0 else disp} & {lab if i==0 else ''} & {u[0]:+.4f} & {u[1]}/{u[2]} & "
                 f"{star(uh)} & {f[0]:+.4f} & {f[1]}/{f[2]} & {star(fh)} \\\\")
    L.append(r"\midrule" if spec=="fg_legacy" else "")
L.append(r"\bottomrule\end{tabular}\end{table}"); L.append("")

# ---- sequential: all nine arms x eight conditions ---------------------------
SIG={"tpe_fg_mo":"fg_legacy","hebo_fg_mo":"fg_legacy","tpe_penult_mo":"fg_penult",
     "hebo_penult_mo":"fg_penult","tpe_hess_mo":"hess_top","hebo_hess_mo":"hess_top"}
ARMS=["random_val","tpe_val","hebo_val","tpe_fg_mo","hebo_fg_mo","tpe_penult_mo",
      "hebo_penult_mo","tpe_hess_mo","hebo_hess_mo"]
SEQC=[("cond7",PRE,"Lipo (mismatch)"),("hydro",PRE,"Hydrophobic Core"),
      ("caco2_random",EX,"Caco2 (random)"),("caco2_scaffold",EX,"Caco2 (scaffold)"),
      ("lipo_random",EX,"Lipo (random)"),("lipo_scaffold",EX,"Lipo (scaffold)"),
      ("amylase",EX,"Amylase"),("gdsc_drug",GDB,"GDSC2")]
def dep(g,s):
    ok=g[(g.status_train=="ok")&g.val_mse_std.notna()]
    if not len(ok): return np.nan
    if s is None: return float(ok.loc[ok.val_mse_std.idxmin(),"test_mse_std"])
    o=ok[ok[s].notna()]
    if not len(o): return np.nan
    return float(o.loc[o.index[int(np.argmin(rankdata(o.val_mse_std)+rankdata(o[s])))],"test_mse_std"])
L.append(r"\begin{table}[htbp]\centering\scriptsize\setlength{\tabcolsep}{3pt}")
L.append(r"\caption{Sequential search, all nine arms, deployment MSE (median over "
         r"replications). Reference is \texttt{tpe\_val}; \textbf{bold} marks arms that "
         r"Holm-beat it within that condition, \underline{underline} marks arms that are "
         r"Holm-worse. Holm is applied over the eight contrasts within each condition.}")
L.append(r"\label{tab:app-seq}")
L.append(r"\begin{tabular}{l"+"r"*len(ARMS)+r"}\toprule")
L.append("condition & "+" & ".join(r"\texttt{%s}"%tex(a.replace("_mo","").replace("_val","")) for a in ARMS)+r" \\\midrule")
for cond,root,disp in SEQC:
    V={a:np.array([dep(pd.read_parquet(f),SIG.get(a)) for f in sorted(glob.glob(f"{root}/{a}/{cond}/*.parquet"))]) for a in ARMS}
    if not len(V.get("tpe_val",[])): continue
    b=V["tpe_val"]; ps,nm=[],[]
    for a in ARMS:
        if a=="tpe_val": continue
        k=min(len(V[a]),len(b)); d=V[a][:k]-b[:k]; d=d[np.isfinite(d)]
        ps.append(float(wilcoxon(d).pvalue) if len(d)>2 and np.any(d!=0) else 1.0)
        nm.append((a,int((d<0).sum())-int((d>0).sum())))
    adj=dict(zip([n for n,_ in nm],holm(ps))); sgn=dict(nm)
    cells=[]
    for a in ARMS:
        m=np.nanmedian(V[a]); t=f"{m:.3f}" if abs(m)<10 else f"{m:.2f}"
        if a!="tpe_val" and adj.get(a,1)<0.05:
            t=r"\textbf{%s}"%t if sgn[a]>0 else r"\underline{%s}"%t
        cells.append(t)
    L.append(f"{disp} & "+" & ".join(cells)+r" \\")
L.append(r"\bottomrule\end{tabular}\end{table}"); L.append("")

# ---- ablations: fixed architecture and validation-free ----------------------
L.append(r"\begin{table}[htbp]\centering\small\setlength{\tabcolsep}{4pt}")
L.append(r"\caption{Ablations, deployment MSE (median over replications). "
         r"\emph{Fixed architecture} pins the network to two hidden layers of width 256. "
         r"\emph{Validation-free} folds the validation split back into training, so only "
         r"train-side selectors are defined and \texttt{Train} replaces \texttt{Val} as the "
         r"reference.}")
L.append(r"\label{tab:app-abl}")
L.append(r"\begin{tabular}{lllrrrr}\toprule")
L.append(r"ablation & condition & reference & ref. & \texttt{Proxy} & $\lambda_{\max}$ & \texttt{random(E)} \\\midrule")
for cond in ["cond7","hydro"]:
    R=runs(f"{ABL}/fixed_arch",cond)
    if len(R)<5: continue
    g=lambda sp: np.median([k.loc[sel(k,sp),"test_mse_std"] for k in R])
    rnd=np.median([k.test_mse_std.mean() for k in R])
    d="Lipo (mismatch)" if cond=="cond7" else "Hydrophobic Core"
    L.append(r"fixed arch. & %s & \texttt{Val} & %.3f & %.3f & %.3f & %.3f \\"%(d,g(None),g("fg_legacy"),g("hess_top"),rnd))
for cond in ["caco2_scaffold","lipo_scaffold","amylase","hydro"]:
    R=runs(f"{ABL}/valfree_pool",cond,need_val=False)
    if len(R)<5: continue
    g=lambda sp: np.median([k.loc[sel(k,sp),"test_mse_std"] for k in R])
    rnd=np.median([k.test_mse_std.mean() for k in R])
    disp={"caco2_scaffold":"Caco2 (scaffold)","lipo_scaffold":"Lipo (scaffold)",
          "amylase":"Amylase","hydro":"Hydrophobic Core"}[cond]
    L.append(r"validation-free & %s & \texttt{Train} & %.3f & %.3f & %.3f & %.3f \\"%(disp,g("__tr"),g("t+fg_legacy"),g("t+hess_top"),rnd))
L.append(r"\bottomrule\end{tabular}\end{table}"); L.append("")

# ---- shift severity ---------------------------------------------------------
L.append(r"\begin{table}[htbp]\centering\small\setlength{\tabcolsep}{4pt}")
L.append(r"\caption{Synthetic shift-severity sweep. $\alpha=0$ is an IID split and "
         r"$\alpha=1$ is pure feature extrapolation; validation is held in-distribution "
         r"throughout. $\rho_{\text{val}}$ degrades with severity, but no threshold appears "
         r"at which the proxy reliably overtakes validation.}")
L.append(r"\label{tab:app-sev}")
L.append(r"\begin{tabular}{lrrrr}\toprule")
L.append(r"condition & $\rho_{\text{val}}$ & \texttt{Val} & \texttt{Proxy} & \texttt{random(E)} \\\midrule")
for ds in ("caco2","lipo"):
    for a in ("000","025","050","075","100"):
        c=f"shiftsev_{ds}_a{a}"; R=runs(SEV,c)
        if len(R)<5: continue
        from scipy.stats import spearmanr
        rv=np.median([spearmanr(k.val_mse_std,k.test_mse_std).statistic for k in R])
        g=lambda sp: np.median([k.loc[sel(k,sp),"test_mse_std"] for k in R])
        rnd=np.median([k.test_mse_std.mean() for k in R])
        L.append(r"%s $\alpha=%.2f$ & %+.2f & %.3f & %.3f & %.3f \\"%(
            ds.capitalize(),int(a)/100,rv,g(None),g("fg_legacy"),rnd))
L.append(r"\bottomrule\end{tabular}\end{table}"); L.append("")

os.makedirs(os.path.dirname(OUT),exist_ok=True)
open(OUT,"w").write("\n".join(L)+"\n")
ntab = sum(1 for x in L if x.startswith("\\begin{table}"))
print("wrote", OUT, "(%d tables)" % ntab)
