#!/usr/bin/env python3
"""Publication figures -> artifacts/results/figures/*.pdf  (vector, grayscale-safe).

Design follows the ICBINB Entropic-award winner (Abe et al., arXiv:2302.00704):
the "do nothing" baseline is drawn as a reference line rather than buried in a
table, panels repeat identically across regimes so a reversal reads as a slope
flip, and paired contrasts stay paired.

All panels use NON-DEGENERATE models only (constant predictors and >50% dead-ReLU
models removed) unless the figure is specifically about degeneracy. Every figure
states its own n.
"""
from __future__ import annotations

import glob
import os
import numpy as np
import pandas as pd
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
from scipy.stats import rankdata, spearmanr

FIG = "artifacts/results/figures"
FIG_ROOT = "artifacts/results/figures"
POOL = "artifacts/results/phase1a_pool/candidates"
FIXED = "artifacts/results/ablations/fixed_arch"
DEAD = 0.5

plt.rcParams.update({
    "font.size": 9, "axes.titlesize": 9.5, "axes.labelsize": 9,
    "xtick.labelsize": 8, "ytick.labelsize": 8, "legend.fontsize": 8,
    "axes.spines.top": False, "axes.spines.right": False,
    "axes.grid": True, "grid.alpha": 0.25, "grid.linewidth": 0.4,
    "figure.dpi": 300, "savefig.dpi": 600, "savefig.bbox": "tight",
    "pdf.fonttype": 42, "ps.fonttype": 42, "svg.fonttype": "none",
})
INK, MUTED, ACCENT = "#1a1a1a", "#8a8a8a", "#000000"


def set_target(sub):
    """Point every subsequent save() at artifacts/results/figures/<sub>/."""
    global FIG
    FIG = os.path.join(FIG_ROOT, sub)
    os.makedirs(FIG, exist_ok=True)


def runs_1b(cond, clean=True):
    """Phase 1B has no shared pool: each (method, outer_run) IS its own 48-trial pool,
    generated by that method's own search. Returns one DataFrame per (method, run) —
    9 methods x 10 runs = 90 pools per condition — so `random(E)` means 'a random pick
    among the trials this search actually produced'."""
    out = []
    for m in SEARCHES:
        for f in sorted(glob.glob(f"{SEQ}/{m}/{cond}/*.parquet")):
            d = pd.read_parquet(f)
            d = d[(d.status_train == "ok") & d.val_mse_std.notna()]
            if clean:
                d = d[(d.pred_std_test >= 1e-6) & (d.dead_relu_frac <= DEAD)]
            if len(d) >= 5:
                out.append(d)
    return out


def save(fig, name):
    """Vector PDF for LaTeX, plus a genuinely high-resolution PNG for viewing.

    The PNG is rendered by matplotlib at 300 dpi rather than by rasterising the PDF
    afterwards -- converting a 72 dpi PDF render and upscaling produces a blurry
    image no matter how good the vector source is."""
    fig.savefig(f"{FIG}/{name}.pdf")
    fig.savefig(f"{FIG}/{name}.png", dpi=300)
    plt.close(fig)
    print(f"{name}.pdf + .png")


COLS = ["condition", "lr", "weight_decay", "dropout", "width", "depth", "dead_relu_frac", "pred_std_test", "test_mse_std", "val_mse_std",
        "train_mse_std", "fg_legacy", "fg_penult", "hess_top", "n_params", "status_train"]
ORDER = ["caco2_random", "caco2_scaffold", "lipo_random", "lipo_scaffold",
         "cond7", "amylase", "hydro"]
NICE_DEFAULT = lambda c: c.replace("_", " ").title()
NICE = {"caco2_random": "Caco2 random\n(IID control)", "caco2_scaffold": "Caco2 scaffold",
        "lipo_random": "Lipo random\n(IID control)", "lipo_scaffold": "Lipo scaffold",
        "cond7": "Cond7\n(ID val, OOD test)", "amylase": "Amylase\n(position shift)",
        "hydro": "Hydro\n(extrapolation)"}


def runs(root, cond, clean=True):
    if root == "__1B__":
        return runs_1b(cond, clean)
    out = []
    for f in sorted(glob.glob(f"{root}/{cond}/*.parquet")):
        d = pd.read_parquet(f, columns=COLS)
        d = d[(d.status_train == "ok") & d.val_mse_std.notna()]
        if clean:
            d = d[(d.pred_std_test >= 1e-6) & (d.dead_relu_frac <= DEAD)]
        if len(d) >= 5:
            out.append(d)
    return out


def pick(k, s):
    if s == "__rand":
        return float(k.test_mse_std.mean())
    if s == "__oracle":
        return float(k.test_mse_std.min())
    if s == "__train":
        return float(k.loc[k.train_mse_std.idxmin(), "test_mse_std"])
    if s is None:
        return float(k.loc[k.val_mse_std.idxmin(), "test_mse_std"])
    if s.startswith("+"):
        c = s[1:]; o = k[k[c].notna()]
        return float(o.iloc[int(np.argmin(rankdata(o.val_mse_std) + rankdata(o[c])))].test_mse_std)
    o = k[k[s].notna()]
    return float(o.loc[o[s].idxmin(), "test_mse_std"])


# Display labels match the paper's terminology; the second element is the internal
# selector spec. Figures and tables must be readable against each other.
SELS = [("Oracle", "__oracle"), ("Val", None), ("Val+Proxy", "+fg_legacy"),
        ("Val+Proxy (pen.)", "+fg_penult"), ("Proxy", "fg_legacy"),
        ("Proxy (penult.)", "fg_penult"), (r"$\lambda_{\max}$", "hess_top"),
        ("Train", "__train"), ("#params", "__np")]


def _np_sel(k, s):
    if s == "__np":
        return float(k.loc[k.n_params.idxmin(), "test_mse_std"])
    return pick(k, s)


def boot_ci(x, n=2000, seed=0):
    r = np.random.default_rng(seed)
    m = np.array([np.median(r.choice(x, len(x), replace=True)) for _ in range(n)])
    return np.percentile(m, 2.5), np.percentile(m, 97.5)


# ------------------------------------------------------------------ figure 1
def fig1():
    n = len(ORDER)
    ncol = 4 if n > 2 else n
    nrow = int(np.ceil((n + (1 if n > 2 else 0)) / ncol))
    fig, axes = plt.subplots(nrow, ncol, figsize=(2.0*ncol, 2.4*nrow), squeeze=False)
    axes = axes.ravel()
    for ax, cond in zip(axes, ORDER):
        R = runs(POOL, cond)
        rnd = np.array([pick(k, "__rand") for k in R])
        names, meds, los, his = [], [], [], []
        for nm, sp in SELS:
            v = np.array([_np_sel(k, sp) for k in R])
            rel = 100.0 * (v - rnd) / rnd           # % vs random selection
            lo, hi = boot_ci(rel)
            names.append(nm); meds.append(np.median(rel)); los.append(lo); his.append(hi)
        y = np.arange(len(names))[::-1]
        for i, nm in enumerate(names):
            is_val = nm == "val"
            ax.plot([los[i], his[i]], [y[i], y[i]], color=INK if is_val else MUTED,
                    lw=1.8 if is_val else 1.0, solid_capstyle="round", zorder=2)
            ax.plot(meds[i], y[i], "o" if is_val else "s",
                    ms=5.5 if is_val else 3.6,
                    mfc=INK if is_val else "white", mec=INK,
                    mew=1.2 if is_val else 0.9, zorder=3)
        ax.axvline(0, color=ACCENT, lw=1.0, ls="--", zorder=1)
        ax.set_yticks(y); ax.set_yticklabels(names)
        ax.set_title(NICE.get(cond, NICE_DEFAULT(cond)) + f"\nn={len(R)} runs", pad=3)
        ax.tick_params(length=2)
    for extra in axes[len(ORDER):]:
        extra.axis("off")
    if len(axes) > len(ORDER):
        axes[-1].text(0.02, 0.72, "worse than\nrandom  →", fontsize=7.5, color=INK)
        axes[-1].text(0.02, 0.45, "← better than\nrandom", fontsize=7.5, color=INK)
        axes[-1].text(0.02, 0.16, "dashed line = picking a\nconfiguration at random",
                      fontsize=6.8, color=MUTED)
    fig.supxlabel("deployed test MSE relative to random selection (%)   ·   "
                  "median with bootstrap 95% CI", fontsize=8, y=-0.02)
    fig.tight_layout()
    save(fig, "fig1_vs_random")


# ------------------------------------------------------------------ figure 3
def fig3():
    """Rank-rank transfer. Validation and test MSE live on very different scales
    under extrapolation (on `hydro`, test loss is ~20x validation loss), so a
    shared-scale identity line is meaningless there. Selection is rank-based
    throughout this study, so the rank-rank view is both the scale-free choice and
    the one that matches the decision actually being made: the diagonal is perfect
    rank transfer, and spread away from it is exactly what makes validation useless."""
    show = [c for c in ["lipo_random", "lipo_scaffold", "cond7", "hydro"] if c in ORDER] or ORDER
    fig, axes = plt.subplots(1, len(show), figsize=(2.0*len(show), 2.5), squeeze=False)
    axes = axes.ravel()
    for ax, cond in zip(axes, show):
        R = runs(POOL, cond)
        rho = float(np.median([spearmanr(k.val_mse_std, k.test_mse_std).statistic for k in R]))
        xs, ys = [], []
        for k in R:                      # rank WITHIN each outer run, then pool
            n = len(k)
            xs.append(rankdata(k.val_mse_std) / n)
            ys.append(rankdata(k.test_mse_std) / n)
        x, y = np.concatenate(xs), np.concatenate(ys)
        ax.scatter(x, y, s=4, alpha=0.22, color=INK, linewidths=0)
        ax.plot([0, 1], [0, 1], ls="--", lw=1.0, color=ACCENT, zorder=3)
        ax.set_xlim(0, 1); ax.set_ylim(0, 1)
        ax.set_xticks([0, .5, 1]); ax.set_yticks([0, .5, 1])
        ax.set_aspect("equal")
        ax.set_title(f"{NICE.get(cond, NICE_DEFAULT(cond)).splitlines()[0]}\n" + r"median $\rho$ = " + f"{rho:+.2f}", pad=3)
        ax.set_xlabel("validation rank")
        ax.tick_params(length=2)
    axes[0].set_ylabel("test rank")
    fig.suptitle("Does the validation ranking survive deployment?   "
                 "(dashed = perfect transfer; best candidate at rank 0)",
                 fontsize=8.5, y=1.02)
    fig.tight_layout()
    save(fig, "fig3_val_on_the_line")


# ------------------------------------------------------------------ figure 4
def fig4():
    dg = [c for c in ["amylase", "hydro", "cond7"] if c in ORDER][:2]
    fig, axes = plt.subplots(1, len(dg), figsize=(3.2*len(dg), 2.8), squeeze=False)
    axes = axes.ravel()
    for ax, cond in zip(axes, dg):
        R = runs(POOL, cond, clean=False)
        d = pd.concat(R)
        degen = (d.pred_std_test < 1e-6).to_numpy()
        ax.scatter(d.dead_relu_frac[~degen], d.test_mse_std[~degen], s=5, alpha=0.25,
                   color=MUTED, linewidths=0, label="ordinary model")
        ax.scatter(d.dead_relu_frac[degen], d.test_mse_std[degen], s=20, alpha=0.9,
                   color=INK, marker="D", linewidths=0,
                   label="constant predictor", zorder=3)
        # how often does the proxy actually SELECT a degenerate model?
        hits = 0
        for k in R:
            o = k[k.fg_legacy.notna()]
            if len(o) and float(o.loc[o.fg_legacy.idxmin(), "pred_std_test"]) < 1e-6:
                hits += 1
        frac = 100.0 * hits / max(len(R), 1)
        ax.set_title(f"{NICE.get(cond, NICE_DEFAULT(cond)).splitlines()[0]}   "
                     f"{100*degen.mean():.0f}% constant", pad=3)
        ax.text(0.03, 0.04, f"the proxy selects a constant\npredictor in {frac:.0f}% of runs",
                transform=ax.transAxes, fontsize=6.8, va="bottom", ha="left",
                bbox=dict(boxstyle="round,pad=0.3", fc="white", ec=INK, lw=0.6, alpha=0.92))
        ax.set_xlabel("fraction of dead ReLU units")
        ax.tick_params(length=2)
    axes[0].set_ylabel("test MSE")
    axes[0].legend(frameon=False, loc="upper left", handletextpad=0.3, borderpad=0.1)
    fig.suptitle("Collapse is rewarded on Amylase but not on Hydrophobic Core",
                 fontsize=8.5, y=1.02)
    fig.tight_layout()
    save(fig, "fig4_degeneracy")


# ------------------------------------------------------------------ figure 5
def fig5():
    cv = [c for c in ["cond7", "hydro"] if c in ORDER] or ORDER[:2]
    fig, axes = plt.subplots(1, len(cv), figsize=(3.2*len(cv), 2.8), squeeze=False)
    axes = axes.ravel()
    for ax, cond in zip(axes, cv):
        R = runs(FIXED, cond)
        d = pd.concat(R)
        rho = spearmanr(d.hess_top, d.test_mse_std).statistic
        ax.scatter(d.hess_top, d.test_mse_std, s=6, alpha=0.35, color=INK,
                   linewidths=0)
        # monotone trend on ranks, drawn in data space via binned medians
        q = pd.qcut(d.hess_top, 12, duplicates="drop")
        g = d.groupby(q, observed=True).agg(x=("hess_top", "median"),
                                            y=("test_mse_std", "median"))
        ax.plot(g.x, g.y, color=ACCENT, lw=1.6, zorder=4)
        ax.set_xscale("log")
        ax.set_title(f"{NICE.get(cond, NICE_DEFAULT(cond)).splitlines()[0]}   " + r"$\rho$ = " + f"{rho:+.2f}", pad=3)
        ax.set_xlabel(r"top Hessian eigenvalue  $\lambda_{\max}$  (sharpness)")
        ax.tick_params(length=2)
    axes[0].set_ylabel("test MSE")
    fig.suptitle("Flat minima under biological extrapolation: the intuition inverts\n"
                 "(fixed architecture 256$\\times$2; line = binned medians)",
                 fontsize=8.5, y=1.02)
    fig.tight_layout()
    save(fig, "fig5_curvature_inversion")




# ------------------------------------------------------------------ figure 6

def _pcorr(d, x, y, ctrl):
    """Spearman partial correlation: rank-residualise both variables on the controls."""
    R = np.column_stack([np.ones(len(d))] + [rankdata(d[c]) for c in ctrl])
    def res(v):
        v = rankdata(v); b, *_ = np.linalg.lstsq(R, v, rcond=None); return v - R @ b
    return spearmanr(res(d[x]), res(d[y])).statistic


SIGS = [("fg_legacy", "fg_legacy"), ("fg_penult", "fg_penult"), ("hess_top", r"$\lambda_{\max}$")]
SHOW4 = ["lipo_scaffold", "cond7", "amylase", "hydro"]


def _clean_pool(root, cond, clean=True):
    R = runs(root, cond, clean=clean)
    return pd.concat(R) if R else None


def fig6():
    """Is activation energy a stand-in for curvature? No -- the apparent relationship
    is learning-rate mediated.

    Marginally the two signals are anti-correlated on every condition. But learning
    rate drives them in opposite directions (large lr finds flatter minima while
    raising activation energy), and conditioning on lr collapses the association to
    near zero on the molecular conditions. Points are shaded by learning rate so the
    reader can see the trend IS the lr gradient rather than an intrinsic coupling."""
    fig, axes = plt.subplots(2, 4, figsize=(8.4, 4.6), sharey="row")
    sm = None
    for r, (sig, lab) in enumerate(SIGS[:2]):
        for c, cond in enumerate(SHOW4):
            ax = axes[r, c]
            d = _clean_pool(POOL, cond)
            d = d[d[sig].notna() & d.hess_top.notna()]
            rho = spearmanr(d.hess_top, d[sig]).statistic
            prho = _pcorr(d, sig, "hess_top", ["width", "depth", "lr"])
            sc = ax.scatter(d.hess_top, d[sig], c=np.log10(d.lr), s=7, alpha=0.75,
                            cmap="cividis", linewidths=0)
            sm = sc
            ax.set_xscale("log"); ax.set_yscale("log")
            ttl = (NICE.get(cond, NICE_DEFAULT(cond)).splitlines()[0] + "\n") if r == 0 else ""
            ax.set_title(ttl + r"$\rho$=" + f"{rho:+.2f}" + r"   $\rho_{|\mathrm{lr}}$=" + f"{prho:+.2f}",
                         pad=3, fontsize=8.5)
            ax.tick_params(length=2)
            if r == 1:
                ax.set_xlabel(r"$\lambda_{\max}$")
        axes[r, 0].set_ylabel(sig)
    cb = fig.colorbar(sm, ax=axes, fraction=0.016, pad=0.012)
    cb.set_label(r"$\log_{10}$ learning rate", fontsize=8.5)
    fig.suptitle("Activation energy is not a curvature proxy: the association is "
                 "learning-rate mediated\n"
                 r"($\rho$ = marginal, $\rho_{|\mathrm{lr}}$ = partial given architecture and lr)",
                 fontsize=9.5, y=1.03)
    save(fig, "fig6_proxy_vs_curvature")


# ------------------------------------------------------------------ figure 7
def fig7():
    """Do any of the signals track the generalisation gap they are supposed to?

    Gap = test MSE - train MSE, both on the train-standardised scale. A signal that
    is useful for deployment should rise with the gap."""
    fig, axes = plt.subplots(3, 4, figsize=(8.0, 6.0))  # independent y: the gap
    # is ~0.5 on the molecular conditions and ~22 on hydro, so a shared row axis
    # would flatten every molecular panel into a line.
    for r, (sig, lab) in enumerate(SIGS):
        for c, cond in enumerate(SHOW4):
            ax = axes[r, c]
            d = _clean_pool(POOL, cond)
            d = d[d[sig].notna()]
            gap = (d.test_mse_std - d.train_mse_std).to_numpy()
            rho = spearmanr(d[sig], gap).statistic
            ax.scatter(d[sig], gap, s=5, alpha=0.30, color=INK, linewidths=0)
            ax.set_xscale("log")
            ax.set_title((NICE.get(cond, NICE_DEFAULT(cond)).splitlines()[0] if r == 0 else "")
                         + ("\n" if r == 0 else "") + r"$\rho$ = " + f"{rho:+.2f}",
                         pad=3, fontsize=9)
            ax.axhline(0, color=MUTED, lw=0.7, ls=":", zorder=1)
            ax.tick_params(length=2)
            if r == 2:
                ax.set_xlabel("signal value")
        axes[r, 0].set_ylabel(f"gap  (test − train)\nvs {sig}")
    fig.suptitle("Do the signals track the generalisation gap?   "
                 "(positive $\\rho$ = larger signal goes with a wider gap)",
                 fontsize=10, y=1.005)
    fig.tight_layout()
    save(fig, "fig7_signals_vs_gap")


# ------------------------------------------------------------------ figure 8
def fig8():
    """Compact summary: every correlation that matters, all seven conditions."""
    rows = [("fg_legacy vs $\\lambda_{\\max}$", lambda d: spearmanr(d.fg_legacy, d.hess_top).statistic),
            ("fg_penult vs $\\lambda_{\\max}$", lambda d: spearmanr(d.fg_penult, d.hess_top).statistic),
            ("fg_legacy vs fg_penult", lambda d: spearmanr(d.fg_legacy, d.fg_penult).statistic),
            (None, None),
            ("fg_legacy vs gap", lambda d: spearmanr(d.fg_legacy, d.test_mse_std - d.train_mse_std).statistic),
            ("fg_penult vs gap", lambda d: spearmanr(d.fg_penult, d.test_mse_std - d.train_mse_std).statistic),
            ("$\\lambda_{\\max}$ vs gap", lambda d: spearmanr(d.hess_top, d.test_mse_std - d.train_mse_std).statistic),
            (None, None),
            ("fg_legacy vs test MSE", lambda d: spearmanr(d.fg_legacy, d.test_mse_std).statistic),
            ("fg_penult vs test MSE", lambda d: spearmanr(d.fg_penult, d.test_mse_std).statistic),
            ("$\\lambda_{\\max}$ vs test MSE", lambda d: spearmanr(d.hess_top, d.test_mse_std).statistic)]
    labels = [r[0] for r in rows]
    M = np.full((len(rows), len(ORDER)), np.nan)
    for j, cond in enumerate(ORDER):
        d = _clean_pool(POOL, cond)
        d = d[d.hess_top.notna() & d.fg_legacy.notna() & d.fg_penult.notna()]
        for i, (nm, fn) in enumerate(rows):
            if fn is not None:
                M[i, j] = fn(d)
    fig, ax = plt.subplots(figsize=(max(3.4, 1.05*len(ORDER)+0.9), 5.0))
    im = ax.pcolormesh(np.arange(M.shape[1]+1)-0.5, np.arange(M.shape[0]+1)-0.5,
                       np.ma.masked_invalid(M), cmap="RdBu_r", vmin=-1, vmax=1,
                       shading="flat", edgecolors="white", linewidth=1.2)
    ax.invert_yaxis()
    ax.set_xticks(range(len(ORDER)))
    ax.set_xticklabels([NICE.get(c, NICE_DEFAULT(c)).splitlines()[0] for c in ORDER], rotation=30, ha="right")
    ax.set_yticks(range(len(rows)))
    ax.set_yticklabels(["" if l is None else l for l in labels])
    for i in range(M.shape[0]):
        for j in range(M.shape[1]):
            if np.isfinite(M[i, j]):
                ax.text(j, i, f"{M[i,j]:+.2f}", ha="center", va="center", fontsize=7.5,
                        color="white" if abs(M[i, j]) > 0.55 else INK)
    ax.set_xticks(np.arange(-.5, len(ORDER), 1), minor=True)
    ax.set_yticks(np.arange(-.5, len(rows), 1), minor=True)
    ax.grid(which="minor", color="white", lw=1.2); ax.grid(which="major", visible=False)
    ax.tick_params(which="minor", length=0)
    cb = fig.colorbar(im, ax=ax, fraction=0.025, pad=0.02)
    cb.set_label("Spearman " + r"$\rho$", fontsize=9)
    ax.set_title("Every correlation that matters, all seven conditions\n"
                 "(non-degenerate models only)", fontsize=10, pad=8)
    fig.tight_layout()
    save(fig, "fig8_correlation_summary")




# ------------------------------------------------------------------ figure 2
SEQ = "artifacts/results/phase1b_sequential/runs"
SEARCHES = ["random_val","tpe_val","hebo_val","tpe_fg_mo","hebo_fg_mo",
            "tpe_penult_mo","hebo_penult_mo","tpe_hess_mo","hebo_hess_mo"]
DEPLOY = [("val+legacy","fg_legacy"),("val+penult","fg_penult"),
          ("val+hess","hess_top"),("train_mse","__train")]


def _deploy(g, sig):
    ok = g[(g.status_train == "ok") & g.val_mse_std.notna()]
    if not len(ok):
        return np.nan
    if sig == "__train":
        return float(ok.loc[ok.train_mse_std.idxmin(), "test_mse_std"])
    if sig is None:
        return float(ok.loc[ok.val_mse_std.idxmin(), "test_mse_std"])
    o = ok[ok[sig].notna()]
    if not len(o):
        return np.nan
    return float(o.iloc[int(np.argmin(rankdata(o.val_mse_std) + rankdata(o[sig])))].test_mse_std)


def fig2():
    """THE central claim: the deploy rule that helps under scaffold mismatch hurts
    under fitness extrapolation, and curvature does the reverse.

    Every stored trial carries val, train and all three signals, so any deploy rule
    can be applied post hoc to ANY search trajectory. Pooling over all nine searches
    (n=90 paired per condition) isolates the deploy rule from the search strategy.
    Identical panel layout across the two conditions so the reversal reads as a
    mirror image, per the ICBINB Entropic-winner's Fig. 2 device."""
    from scipy.stats import wilcoxon
    fig, axes = plt.subplots(1, 2, figsize=(7.2, 2.9), sharex=False)
    for ax, cond, title in zip(axes, ["cond7", "hydro"],
                               ["Cond7  (scaffold mismatch)", "Hydro  (fitness extrapolation)"]):
        dfs = {m: [pd.read_parquet(f) for f in sorted(glob.glob(f"{SEQ}/{m}/{cond}/*.parquet"))]
               for m in SEARCHES}
        base = np.concatenate([[_deploy(g, None) for g in dfs[m]] for m in SEARCHES])
        rows = []
        for name, sig in DEPLOY:
            v = np.concatenate([[_deploy(g, sig) for g in dfs[m]] for m in SEARCHES])
            d = v - base
            ok = np.isfinite(d)
            d = d[ok]
            pct = 100.0 * d / np.median(base)
            p = float(wilcoxon(d).pvalue) if np.any(d != 0) else 1.0
            rows.append((name, float(np.median(pct)), int((d < 0).sum()), int((d > 0).sum()), p,
                         boot_ci(pct)))
        y = np.arange(len(rows))[::-1]
        for i, (nm, med, b, w, p, (lo, hi)) in enumerate(rows):
            # decide fill by the WIN/LOSS direction, not the median: rank-sum ties
            # with `val` on many runs, so the median % can sit at exactly 0 while the
            # paired test is decisive (e.g. cond7 val+legacy: median 0.00, 43/25, p<.001)
            helps = b > w
            ax.plot([lo, hi], [y[i], y[i]], color=INK, lw=1.4, solid_capstyle="round", zorder=2)
            ax.plot(med, y[i], "o" if helps else "s", ms=7,
                    mfc=INK if helps else "white", mec=INK, mew=1.4, zorder=3)
            star = "***" if p < 0.001 else ("**" if p < 0.01 else ("*" if p < 0.05 else ""))
            ax.text(1.02, y[i], f"{b}/{w}{star}", transform=ax.get_yaxis_transform(),
                    va="center", fontsize=7, color=INK)
        ax.axvline(0, color=ACCENT, lw=1.1, ls="--", zorder=1)
        ax.set_yticks(y); ax.set_yticklabels([r[0] for r in rows])
        ax.set_title(title, pad=4)
        ax.set_xlabel("deployed loss vs `val` alone (%)")
        ax.tick_params(length=2)
        ax.set_ylim(-0.7, len(rows) - 0.3)
    axes[0].plot([], [], "o", ms=6, mfc=INK, mec=INK, label="helps")
    axes[0].plot([], [], "s", ms=6, mfc="white", mec=INK, mew=1.4, label="hurts")
    axes[0].legend(frameon=False, loc="lower right", handletextpad=0.3,
                   borderpad=0.1, fontsize=7)
    fig.suptitle("The same augmentation helps under one biological shift and hurts under the other\n"
                 "pooled over all 9 search strategies (n=90 paired); counts are better/worse, "
                 "* p<.05  ** p<.01  *** p<.001",
                 fontsize=9, y=1.10)
    fig.tight_layout()
    save(fig, "fig2_signflip")


# ------------------------------------------------------------------ figure 9
def fig9():
    """Does a larger search budget help? Prefixes of the SAME runs, so this is not
    a separate shorter experiment — the sampler saw trials in `trial_index` order."""
    NAT = {"tpe_fg_mo":"fg_legacy","hebo_fg_mo":"fg_legacy","tpe_penult_mo":"fg_penult",
           "hebo_penult_mo":"fg_penult","tpe_hess_mo":"hess_top","hebo_hess_mo":"hess_top"}
    B = [8, 16, 24, 48]
    fig, axes = plt.subplots(1, 2, figsize=(7.0, 2.8))
    for ax, cond, title in zip(axes, ["cond7", "hydro"],
                               ["Cond7  (scaffold mismatch)", "Hydro  (fitness extrapolation)"]):
        for m in SEARCHES:
            fs = sorted(glob.glob(f"{SEQ}/{m}/{cond}/*.parquet"))
            if not fs:
                continue
            dfs = [pd.read_parquet(f) for f in fs]
            sig = NAT.get(m)
            ys = [np.median([_deploy(g[g.trial_index < b], sig) for g in dfs]) for b in B]
            val_only = m.endswith("_val")
            ax.plot(B, ys, marker="o" if val_only else "s", ms=3.5,
                    lw=1.6 if val_only else 1.0,
                    color=INK if val_only else MUTED,
                    alpha=1.0 if val_only else 0.75, zorder=3 if val_only else 2)
        ax.set_xticks(B); ax.set_xlabel("search budget (trials)")
        ax.set_title(title, pad=4); ax.tick_params(length=2)
    axes[0].set_ylabel("median deployed test MSE")
    axes[0].plot([], [], color=INK, marker="o", ms=3.5, lw=1.6, label="validation-only search")
    axes[0].plot([], [], color=MUTED, marker="s", ms=3.5, lw=1.0, label="proxy-steered search")
    axes[0].legend(frameon=False, loc="best")
    fig.suptitle("Six times the search budget buys nothing under extrapolation\n"
                 "prefixes of the same runs; lower is better",
                 fontsize=9, y=1.09)
    fig.tight_layout()
    save(fig, "fig9_budget")


SOURCES = {
    # sub-folder      pool root                                  conditions shown
    "phase1a": (POOL,     ORDER,                              ["lipo_scaffold","cond7","amylase","hydro"],
                "Phase 1A — one shared 48-model pool ranked by every selector"),
    "phase1b": ("__1B__", ["cond7","hydro"],                  ["cond7","hydro"],
                "Phase 1B — each (method, run) is its own 48-trial search-generated pool"),
}


def render(sub):
    """Emit the full figure set for one source into figures/<sub>/."""
    global POOL, ORDER, SHOW4, FIXED, SRC_LABEL
    root, conds, show4, label = SOURCES[sub]
    POOL, ORDER_, SHOW4_ = root, conds, show4
    globals()["POOL"] = root
    globals()["ORDER"] = conds
    globals()["SHOW4"] = show4
    globals()["SRC_LABEL"] = label
    # fig5 (curvature) uses fixed_arch for 1A; for 1B use 1B's own pool
    globals()["FIXED"] = FIXED_ARCH if sub == "phase1a" else "__1B__"
    set_target(sub)
    for fn in (fig1, fig3, fig4, fig5, fig6, fig7, fig8):
        try:
            fn()
        except Exception as e:
            print(f"  [{sub}] {fn.__name__} skipped: {type(e).__name__}: {e}")


if __name__ == "__main__":
    FIXED_ARCH = FIXED
    POOL_1A, ORDER_1A = POOL, ORDER
    for sub in ("phase1a", "phase1b"):
        print(f"--- {sub} ---")
        render(sub)
    # Phase-1B-only figures (no Phase-1A analogue: they need search trajectories)
    globals()["POOL"], globals()["ORDER"] = POOL_1A, ORDER_1A
    set_target("phase1b")
    fig2(); fig9()
    print(f"\nwrote to {FIG_ROOT}/phase1a/ and {FIG_ROOT}/phase1b/")
    print("\nwrote to", FIG)
