#!/usr/bin/env python3
"""Emit the paper's appendix data tables as LaTeX, straight from the parquet trees.

Generated rather than transcribed: every number in the appendix therefore agrees with
RESULTS_BY_DATASET.md and RESULTS_MASTER.md by construction, and re-running after a
new experiment updates the paper instead of silently going stale.
"""
from __future__ import annotations
import glob, os
import numpy as np, pandas as pd
from scipy.stats import wilcoxon, rankdata, spearmanr

OUT = "Formatting_Instructions_For_ICBINB_Failure_Modes_in_AI_for_Biology___NeurIPS_2026/appendix_tables.tex"
P1A = "artifacts/results/phase1a_pool/candidates"
GD  = "artifacts/results/exploratory/gdsc/phase1a/candidates"
ABL = "artifacts/results/ablations"
TR  = "artifacts/results/exploratory/trace/candidates"

def tex(s):  # condition / selector names -> LaTeX-safe
    return s.replace("_", r"\_")

def holm(p):
    p = np.asarray(p, float); n = len(p); a = np.empty(n); r = 0.0
    for i, k in enumerate(np.argsort(p)):
        r = max(r, (n - i) * p[k]); a[k] = min(r, 1.0)
    return a

SELS = [("oracle","__or"),("val",None),("val+legacy","+fg_legacy"),("val+penult","+fg_penult"),
        ("val+hess","+hess_top"),("fg_legacy","fg_legacy"),("fg_penult","fg_penult"),
        ("hess_top","hess_top"),("train_mse","__tr"),("n_params","__np"),("random(E)","__rand")]
METRICS = [("test_mse_std","MSE",False),("test_mae_raw","MAE",False),("test_spearman",r"$\rho$",True)]
CONDS = [("caco2_random",P1A),("caco2_scaffold",P1A),("lipo_random",P1A),("lipo_scaffold",P1A),
         ("cond7",P1A),("amylase",P1A),("hydro",P1A),("gdsc_drug",GD)]

def sel_idx(k, s):
    if s is None: return k.val_mse_std.idxmin()
    if s == "__tr": return k.train_mse_std.idxmin()
    if s == "__np": return k.n_params.idxmin()
    if s == "__or": return k.test_mse_std.idxmin()
    if s.startswith("t+"):
        c = s[2:]; o = k[k[c].notna()]
        return o.index[int(np.argmin(rankdata(o.train_mse_std) + rankdata(o[c])))]
    if s.startswith("+"):
        c = s[1:]; o = k[k[c].notna()]
        return o.index[int(np.argmin(rankdata(o.val_mse_std) + rankdata(o[c])))]
    o = k[k[s].notna()]; return o[s].idxmin()

def runs(root, cond, need_val=True, filt=True):
    out = []
    for f in sorted(glob.glob(f"{root}/{cond}/*.parquet")):
        d = pd.read_parquet(f); d = d[d.status_train == "ok"]
        d = d[d.val_mse_std.notna()] if need_val else d[d.train_mse_std.notna()]
        if filt: d = d[(d.pred_std_test >= 1e-6) & (d.dead_relu_frac <= 0.5)]
        if len(d) >= 5: out.append(d)
    return out

def pick(R, sp, col):
    if sp == "__rand": return np.array([k[col].mean() for k in R])
    return np.array([k.loc[sel_idx(k, sp), col] for k in R], float)

L = [r"% AUTO-GENERATED by scripts_icbinb/make_appendix_tex.py -- do not hand-edit.", ""]

# ---------------- C.1 full shared-pool table, per condition -------------------
L.append(r"\subsection{Complete shared-pool results (all selectors, all conditions)}")
L.append(r"\label{app:pool-full}")
L.append("Median deployment MSE with interquartile range over outer runs, paired median "
         r"difference $\Delta$ against \texttt{val}, win/loss counts, raw Wilcoxon $p$, and "
         r"Holm-adjusted $p$ within each condition's selector family. Degeneracy-filtered "
         r"(\S\ref{app:degen}).")
L.append("")
for cond, root in CONDS:
    R = runs(root, cond)
    if len(R) < 5: continue
    base = pick(R, None, "test_mse_std")
    rows, ps = [], []
    for nm, sp in SELS:
        v = pick(R, sp, "test_mse_std")
        q1, q3 = np.percentile(v, [25, 75])
        if nm == "val":
            rows.append((nm, f"{np.median(v):.4f} [{q1:.4f}, {q3:.4f}]", "--", "--", "--")); continue
        d = v - base; d = d[np.isfinite(d)]
        p = float(wilcoxon(d).pvalue) if len(d) > 2 and np.any(d != 0) else 1.0
        ps.append(p)
        rows.append((nm, f"{np.median(v):.4f} [{q1:.4f}, {q3:.4f}]",
                     f"{np.median(d):+.4f}", f"{int((d<0).sum())}/{int((d>0).sum())}", f"{p:.3f}"))
    adj = holm(ps); it = iter(adj)
    L.append(r"\begin{table}[htbp]\centering\scriptsize\setlength{\tabcolsep}{3pt}")
    L.append(r"\caption{Shared pool, \texttt{%s} (%d outer runs, median %d/48 candidates kept).}"
             % (tex(cond), len(R), int(np.median([len(k) for k in R]))))
    L.append(r"\label{tab:app-pool-%s}" % cond.replace("_", "-"))
    L.append(r"\begin{tabular}{lrrrrr}\toprule")
    L.append(r"selector & median [IQR] & $\Delta$ vs \texttt{val} & w/l & $p$ & $p_{\text{Holm}}$ \\\midrule")
    for nm, med, dd, bw, p in rows:
        ph = "--" if p == "--" else f"{next(it):.3f}"
        L.append(r"\texttt{%s} & %s & %s & %s & %s & %s \\" % (tex(nm), med, dd, bw, p, ph))
    L.append(r"\bottomrule\end{tabular}\end{table}")
    L.append("")

# ---------------- C.2 metric robustness ---------------------------------------
L.append(r"\subsection{Metric robustness of every selector}")
L.append(r"\label{app:metric}")
L.append(r"Selectors that beat \texttt{val} at Holm-adjusted $\alpha=0.05$, by the metric "
         r"used to score the deployed model. Selection rules are identical across columns.")
L.append(r"\begin{table}[htbp]\centering\scriptsize\setlength{\tabcolsep}{3pt}")
L.append(r"\caption{Metric robustness. MSE is train-$\sigma$ standardised; MAE is what the "
         r"TDC leaderboards report; $\rho$ is Spearman, what FLIP2 reports.}")
L.append(r"\label{tab:app-metric}")
L.append(r"\begin{tabular}{llll}\toprule")
L.append(r"condition & under MSE & under MAE & under $\rho$ \\\midrule")
for cond, root in CONDS:
    R = runs(root, cond)
    if len(R) < 5: continue
    cells = []
    for col, _, hib in METRICS:
        base = pick(R, None, col); ps, nm_ = [], []
        for nm, sp in SELS:
            if nm in ("val", "oracle", "random(E)"): continue
            v = pick(R, sp, col); d = (base - v) if hib else (v - base); d = d[np.isfinite(d)]
            if not len(d): continue
            ps.append(float(wilcoxon(d).pvalue) if np.any(d != 0) else 1.0)
            nm_.append((nm, int((d < 0).sum()) - int((d > 0).sum())))
        adj = holm(ps)
        win = [tex(n) for (n, s), a in zip(nm_, adj) if a < 0.05 and s > 0]
        cells.append(", ".join(r"\texttt{%s}" % w for w in win) or "--")
    L.append(r"\texttt{%s} & %s & %s & %s \\" % (tex(cond), *cells))
L.append(r"\bottomrule\end{tabular}\end{table}")
L.append("")

# ---------------- E degeneracy ------------------------------------------------
L.append(r"\subsection{Degeneracy audit}")
L.append(r"\label{app:degen}")
L.append(r"\begin{table}[htbp]\centering\scriptsize\setlength{\tabcolsep}{3pt}")
L.append(r"\caption{Degeneracy by condition, computed \emph{before} filtering. "
         r"``const.'' is the fraction of candidates with $\mathrm{std}(\hat y)<10^{-6}$; "
         r"``dead$>$0.5'' the fraction with more than half their ReLU units permanently "
         r"inactive; ``dead@FG'' the median dead-unit fraction of the model "
         r"\texttt{fg\_legacy} selects.}")
L.append(r"\label{tab:app-degen}")
L.append(r"\begin{tabular}{lrrrr}\toprule")
L.append(r"condition & const. & dead$>$0.5 & median dead & dead@FG \\\midrule")
for cond, root in CONDS:
    R = runs(root, cond, filt=False)
    if len(R) < 5: continue
    pool = pd.concat(R)
    sel = np.array([k.loc[k.fg_legacy.idxmin(), "dead_relu_frac"] for k in R], float)
    L.append(r"\texttt{%s} & %.1f\%% & %.1f\%% & %.3f & \textbf{%.3f} \\" % (
        tex(cond), 100 * (pool.pred_std_test < 1e-6).mean(),
        100 * (pool.dead_relu_frac > 0.5).mean(),
        float(pool.dead_relu_frac.median()), float(np.median(sel))))
L.append(r"\bottomrule\end{tabular}\end{table}")
L.append("")

# ---------------- F hyperparameter mechanism ----------------------------------
L.append(r"\subsection{What validation selects versus what deployment wants}")
L.append(r"\label{app:hp}")
L.append(r"\begin{table}[htbp]\centering\scriptsize\setlength{\tabcolsep}{3pt}")
L.append(r"\caption{Median paired hyperparameter difference between the selected model and "
         r"the deployment oracle in the same pool. Positive $\Delta\log_{10}\eta$ means the "
         r"oracle prefers a larger learning rate.}")
L.append(r"\label{tab:app-hp}")
L.append(r"\begin{tabular}{llrrrr}\toprule")
L.append(r"condition & selector & $\Delta\log_{10}\eta$ & $\Delta\log_2 w$ & $\Delta$dropout & $\Delta$wd \\\midrule")
for cond, root in CONDS:
    R = runs(root, cond)
    if len(R) < 5: continue
    for nm, sp in [("val", None), ("n_params", "__np")]:
        dl, dw, dd, dwd = [], [], [], []
        for k in R:
            s = k.loc[sel_idx(k, sp)]; o = k.loc[sel_idx(k, "__or")]
            dl.append(np.log10(o.lr) - np.log10(s.lr)); dw.append(np.log2(o.width) - np.log2(s.width))
            dd.append(o.dropout - s.dropout); dwd.append(o.weight_decay - s.weight_decay)
        L.append(r"\texttt{%s} & \texttt{%s} & %+.3f & %+.2f & %+.3f & %+.1e \\" % (
            tex(cond), tex(nm), np.median(dl), np.median(dw), np.median(dd), np.median(dwd)))
L.append(r"\bottomrule\end{tabular}\end{table}")
L.append("")

# ---------------- G geometry / curvature --------------------------------------
def partial(df, a, b, ctrl=("lr", "width", "depth")):
    keep = df[[a, b, *ctrl]].replace([np.inf, -np.inf], np.nan).dropna()
    if len(keep) < 10: return np.nan, np.nan
    R_ = np.column_stack([rankdata(keep[c]) for c in (a, b, *ctrl)])
    C = np.column_stack([np.ones(len(R_)), R_[:, 2:]])
    res = [R_[:, i] - C @ np.linalg.lstsq(C, R_[:, i], rcond=None)[0] for i in (0, 1)]
    return float(spearmanr(keep[a], keep[b]).statistic), float(spearmanr(res[0], res[1]).statistic)

L.append(r"\subsection{Geometry and curvature diagnostics}")
L.append(r"\label{app:geom}")
L.append(r"\begin{table}[htbp]\centering\scriptsize\setlength{\tabcolsep}{3pt}")
L.append(r"\caption{Activation energy against exact curvature and against the "
         r"generalisation gap. ``marg.'' is the marginal Spearman correlation across the "
         r"sweep; ``partial'' additionally residualises on learning rate, width and depth. "
         r"The learning rate is the confounder: it raises activation energy while lowering "
         r"$\lambda_{\max}$, manufacturing the marginal association.}")
L.append(r"\label{tab:app-geom}")
L.append(r"\begin{tabular}{lrrrrrr}\toprule")
L.append(r" & \multicolumn{2}{c}{$P_{\text{act}}\sim\lambda_{\max}$} & "
         r"\multicolumn{2}{c}{$P_{\text{act}}\sim$ gap} & \multicolumn{2}{c}{$\lambda_{\max}\sim$ gap} \\")
L.append(r"\cmidrule(lr){2-3}\cmidrule(lr){4-5}\cmidrule(lr){6-7}")
L.append(r"condition & marg. & partial & marg. & partial & marg. & partial \\\midrule")
for cond, root in CONDS:
    R = runs(root, cond)
    if len(R) < 5: continue
    d = pd.concat(R); d = d.assign(gap=d.test_mse_std - d.train_mse_std)
    a1, p1 = partial(d, "fg_legacy", "hess_top")
    a2, p2 = partial(d, "fg_legacy", "gap")
    a3, p3 = partial(d, "hess_top", "gap")
    if not np.isfinite(p1): continue
    L.append(r"\texttt{%s} & %+.2f & %+.2f & %+.2f & %+.2f & %+.2f & %+.2f \\"
             % (tex(cond), a1, p1, a2, p2, a3, p3))
L.append(r"\bottomrule\end{tabular}\end{table}")
L.append("")

# ---------------- G.3/G.4 trace + relative flatness ---------------------------
L.append(r"\begin{table}[htbp]\centering\scriptsize\setlength{\tabcolsep}{3pt}")
L.append(r"\caption{Hessian trace and approximate relative flatness, "
         r"$\lVert w\rVert^2\operatorname{tr}(H)$, on the three conditions where the trace "
         r"was measured (720 networks, Hutchinson with 30 Rademacher probes). All entries "
         r"are partial Spearman correlations with the generalisation gap given learning "
         r"rate, width and depth. The final row shows that the trace adds almost nothing "
         r"once the weight norm is controlled.}")
L.append(r"\label{tab:app-trace}")
TC = ["caco2_scaffold", "cond7", "hydro"]
have = {}
for c in TC:
    R = runs(TR, c)
    if R:
        d = pd.concat(R)
        have[c] = d.assign(gap=d.test_mse_std - d.train_mse_std,
                           petzka=d.weight_norm_fro ** 2 * d.hess_trace,
                           w2=d.weight_norm_fro ** 2)
if have:
    L.append(r"\begin{tabular}{l%s}\toprule" % ("r" * len(have)))
    L.append("quantity & " + " & ".join(r"\texttt{%s}" % tex(c) for c in have) + r" \\\midrule")
    for lab, col, ctrl in [(r"$\lambda_{\max}$", "hess_top", None),
                           (r"$\operatorname{tr}(H)$", "hess_trace", None),
                           (r"$\lVert w\rVert^2\operatorname{tr}(H)$", "petzka", None),
                           (r"$\lVert w\rVert^2$ alone", "w2", None),
                           (r"$P_{\text{act}}$ (ours)", "fg_legacy", None),
                           (r"$\operatorname{tr}(H)$ given $\lVert w\rVert^2$", "hess_trace",
                            ("lr", "width", "depth", "w2"))]:
        cells = []
        for c, d in have.items():
            _, p = partial(d, col, "gap", ctrl) if ctrl else partial(d, col, "gap")
            cells.append(f"{p:+.2f}")
        L.append(lab + " & " + " & ".join(cells) + r" \\")
    L.append(r"\midrule")
    for lab, f in [(r"median $\lambda_{\max}/\operatorname{tr}(H)$",
                    lambda d: np.median(d.hess_top / d.hess_trace)),
                   (r"Hutchinson rel.\ SE", lambda d: np.median(d.hess_trace_se / d.hess_trace.abs())),
                   (r"$P_{\text{act}}\sim\operatorname{tr}(H)$ (partial)",
                    lambda d: partial(d, "fg_legacy", "hess_trace")[1]),
                   (r"$P_{\text{act}}\sim\lVert w\rVert^2\operatorname{tr}(H)$ (partial)",
                    lambda d: partial(d, "fg_legacy", "petzka")[1])]:
        L.append(lab + " & " + " & ".join(f"{f(d):+.3f}" for d in have.values()) + r" \\")
    L.append(r"\bottomrule\end{tabular}")
L.append(r"\end{table}")
L.append("")

os.makedirs(os.path.dirname(OUT), exist_ok=True)
open(OUT, "w").write("\n".join(L) + "\n")
print(f"wrote {OUT} ({len(L)} lines, "
      f"{sum(1 for x in L if x.startswith(chr(92)+'begin{table}'))} tables)")
